'// test comment
FUNCTION TEST(I AS INTEGER) AS INTEGER
 PRINT I
 RETURN 0
END FUNCTION
function myMOD(N AS INTEGER, B AS INTEGER) AS INTEGER
DIM RESULT AS INTEGER
DIM FRACT AS SINGLE
DIM IPROD AS INTEGER
DIM IWHOLE AS INTEGER
FRACT = N/B
IWHOLE = INT(FRACT)
RESULT = N - IWHOLE * B
RETURN RESULT
END FUNCTION
DIM I AS INTEGER
DIM J AS INTEGER
J = myMOD(15,2)
PRINT "MOD 15,2 IS ", J
'print pi(4)
FOR I = 1 TO 100
PRINT I
NEXT I
END
